export const error_def = {
    INVALID_EMAIL: 'Invalid_Email_Address',
    INVALID_PASSWORD_LENGTH: 'Invalid_Password_Length',
    INVALID_PASSWORD: 'Invalid_Password',
    INVALID_NAME: 'Invalid_Name',
    INVALID_UPDATE: 'Invalid_User_Update',
    EMAIL_ALREADY_EXISTS: 'Email_Already_Exists',
    ROUTE_NOT_FOUND: 'Route_Not_Found',
    ERROR_FILE_UPLOAD: 'Error_File_Upload',
    INVALID_FILE_TYPE: 'Invalid_File_Type',
    SERVER_ERROR: 'Server_Error',
    USER_NOT_FOUND: 'User_Not_Found',
    INVALID_REDIRECT: 'Invalid_Redirect',
    INVALID_REQUEST_TOKEN: "Invalid_Request_Token",
    INVALID_REQUEST_LIMIT: "Invalid_Request_Limit",
    INVALID_REQUEST_SORT: "Invalid_Request_Sort",
    INVALID_REQUEST_ORDER: "Invalid_Request_Order",
    INVALID_REQUEST_FILTER: "Invalid_Request_Filter",
    INVALID_REQUEST_TASK_ID: "Invalid_Request_Task_Id",
    INVALID_TASK_OBJECTIVE: "Invalid_Task_Objective",
    INVALID_TASK_DATE: "Invalid_Task_Date",
    TASK_NOT_FOUND: "Task_Not_Found",
    API_RATE_LIMIT: "Api_Rate_Limit"
}